apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker-resume
  labels:
    app: ai-worker-resume
    tier: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-worker-resume
  template:
    metadata:
      labels:
        app: ai-worker-resume
        tier: worker
    spec:
      containers:
        - name: worker-resume
          image: 209192769586.dkr.ecr.ap-northeast-2.amazonaws.com/scuad-ai-worker-resume:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ai-shared-secret
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
