apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets-dev
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
spec:
  project: default
  source:
    repoURL: "https://github.com/100-hours-a-week/11-team-service-cloud.git"
    targetRevision: develop
    path: k8s/monitoring/secrets/dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
