apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - presync-fetch-secret.yaml
namespace: prod
images:
  - name: 209192769586.dkr.ecr.ap-northeast-2.amazonaws.com/scuad-ai-api
    newTag: main-0a76bf2
  - name: 209192769586.dkr.ecr.ap-northeast-2.amazonaws.com/scuad-ai-worker-resume
    newTag: main-0a76bf2
  - name: 209192769586.dkr.ecr.ap-northeast-2.amazonaws.com/scuad-ai-worker-job
    newTag: main-0a76bf2
  - name: 209192769586.dkr.ecr.ap-northeast-2.amazonaws.com/scuad-ai-worker-evaluate
    newTag: main-0a76bf2
  - name: 209192769586.dkr.ecr.ap-northeast-2.amazonaws.com/scuad-ai-worker-compare
    newTag: main-0a76bf2
