apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spring-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: spring-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /scuad/v3/dev/be/DOT_ENV
