apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: web-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: web-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /scuad/v3/dev/fe/DOT_ENV
