apiVersion: v1                   # 이 리소스의 API 버전 (v1은 기본 Pod API 그룹)
kind: Pod                        # 생성할 리소스의 종류는 Pod
metadata:                        # 생성할 리소스의 메타데이터
  name: web             # 생성될 Pod의 이름
  namespace: dev
  labels:                        # Pod에 부여할 라벨(선택적, 식별 및 선택자에 사용)
    app: scuad            # 라벨 키:값 쌍 (예: 서비스 또는 셀렉터에 활용)
spec:                            # 이 Pod의 사양 정의 시작
  containers:                    # Pod에 포함될 컨테이너 목록
    - name: web              # 첫 번째(그리고 유일한) 컨테이너의 이름
      image: 209192769586.dkr.ecr.ap-northeast-2.amazonaws.com/scuad-frontend:latest  # 사용할 컨테이너 이미지 (Docker Hub 또는 Container Registry 경로)
      ports:                     # 이 컨테이너가 외부에 노출할 포트 목록
        - containerPort: 80    # 컨테이너 내부에서 서비스가 사용하는 포트 (예: Express.js 앱이 3000번 포트에서 listen 중)