name: FastAPI CI

on:
  workflow_dispatch: # 수동 실행
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md" # 문서 변경 무시
      # - ".github/**" # 워크플로우 변경 무시
      # - ".git*" # Git 설정 변경 무시

permissions:
  id-token: write # required to get OIDC token
  contents: read # required to check out repository content

jobs:
  # ----------------------------
  # 1. Build
  # ----------------------------
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.meta.outputs.artifact_name }}
      version: ${{ steps.meta.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Create .env file
        run: |
          # Weaviate Configs
          echo "WEAVIATE_HOST=${{ secrets.WEAVIATE_HOST }}" >> .env
          echo "WEAVIATE_PORT=${{ secrets.WEAVIATE_PORT }}" >> .env
          echo "WEAVIATE_GRPC_PORT=${{ secrets.WEAVIATE_GRPC_PORT }}" >> .env
          
          # DB Configs
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          
          # LLM Configs
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "EMBEDDING_MODEL=${{ secrets.EMBEDDING_MODEL }}" >> .env
          
          # Langfuse Configs
          echo "LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }}" >> .env
          echo "LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }}" >> .env
          echo "LANGFUSE_BASE_URL=${{ secrets.LANGFUSE_BASE_URL }}" >> .env
          
          # AWS S3 Configs
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env

      - name: Import Check
        run: uv run python -c "import api.main"

      
      - name: Debug - confirm .env exists
        run: |
          pwd
          ls -al .env
          head -n 3 .env

      - name: Set metadata (artifact name / version)
        id: meta
        run: |
          VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          ARTIFACT_NAME="ai-${VERSION}-${GITHUB_SHA::7}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "artifact_name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

      - name: Upload source snapshot (temporary for downstream job)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.meta.outputs.artifact_name }}
          include-hidden-files: true
          if-no-files-found: error
          path: |
            api
            shared
            pipelines
            pyproject.toml
            uv.lock
            pytest.ini
            README.md
            .env
          retention-days: 1

  # ----------------------------
  # 2. Test
  # ----------------------------
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enable-cache: true
          
      - name: Create .env file
        run: |
          # Weaviate Configs
          echo "WEAVIATE_HOST=${{ secrets.WEAVIATE_HOST }}" >> .env
          echo "WEAVIATE_PORT=${{ secrets.WEAVIATE_PORT }}" >> .env
          echo "WEAVIATE_GRPC_PORT=${{ secrets.WEAVIATE_GRPC_PORT }}" >> .env
          
          # DB Configs
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          
          # LLM Configs
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "EMBEDDING_MODEL=${{ secrets.EMBEDDING_MODEL }}" >> .env
          
          # Langfuse Configs
          echo "LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }}" >> .env
          echo "LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }}" >> .env
          echo "LANGFUSE_BASE_URL=${{ secrets.LANGFUSE_BASE_URL }}" >> .env
          
          # AWS S3 Configs
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env

      - name: Install dependencies
        run: uv sync --frozen

      - name: Smoke tests (develop)
        if: ${{ github.base_ref == 'develop' || (github.event_name == 'workflow_dispatch' && github.ref_name == 'develop')}}
        run: uv run pytest

  # ----------------------------
  # 3. Static Analysis
  # ----------------------------
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.base_ref == 'develop' || (github.event_name == 'workflow_dispatch' && github.ref_name == 'develop')}}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Ruff (lint)
        run: uv run ruff check .

      - name: Black (format check)
        run: uv run black --check .

      - name: MyPy (type check)
        run: uv run mypy .
        continue-on-error: true

  # ----------------------------
  # 4. Main -> S3 snapshot Archive (develop)
  # ----------------------------
  snapshot_archive:
    name: Archive to S3
    runs-on: ubuntu-latest
    needs: [build, test, static_analysis]
    if: ${{ github.base_ref == 'develop'  || (github.event_name == 'workflow_dispatch' && github.ref_name == 'develop')}}

    steps:
      - name: Set meta
        id: meta
        run: |
          echo "timestamp=$(TZ='Asia/Seoul' date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: artifact

      - name: Debug - confirm .env before S3 upload
        run: |
          echo "== local files =="
          ls -al artifact
          echo "== check .env =="
          ls -al artifact/.env
          echo "== size =="
          wc -c artifact/.env


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      - name: Upload snapshot to S3
        env:
          BUCKET: ${{ secrets.RELEASE_BUCKET }}
          PREFIX: snapshots/ai
        run: |
          # 타임스탬프 폴더에 저장 (빌드 히스토리)
          aws s3 cp artifact/ \
            s3://$BUCKET/$PREFIX/${{ needs.build.outputs.version }}/${{ steps.meta.outputs.timestamp }}/ \
            --recursive

          # latest 폴더에 덮어쓰기 (최신 스냅샷)
          aws s3 cp artifact/ \
            s3://$BUCKET/$PREFIX/latest/ \
            --recursive


  # -----------------------------------
  # 5. Main -> S3 Release Archive (main)
  # -------------------------------------
  release_archive:
    name: Archive release to S3
    runs-on: ubuntu-latest
    needs: [build, test]
    if: ${{ github.base_ref == 'main'  || (github.event_name == 'workflow_dispatch' && github.ref_name == 'main') }}

    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: artifact

      - name: Debug - confirm .env before S3 upload
        run: |
          echo "== local files =="
          ls -al artifact
          echo "== check .env =="
          ls -al artifact/.env
          echo "== size =="
          wc -c artifact/.env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2
      
      - name: Upload release to S3
        env:
          BUCKET: ${{ secrets.RELEASE_BUCKET }}
          PREFIX: releases/ai
        run: |
          # 버전 폴더에 저장 (버전당 하나)
          aws s3 cp artifact/ \
            s3://$BUCKET/$PREFIX/${{ needs.build.outputs.version }}/ \
            --recursive

          # latest 폴더에 덮어쓰기 (최신 릴리즈)
          aws s3 cp artifact/ \
            s3://$BUCKET/$PREFIX/latest/ \
            --recursive