# Backend

name: Backend CI

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  id-token: write # required to get OIDC token
  contents: read # required to check out repository content

jobs:
  # ----------------------------
  # 1. Build (테스트 제외)
  # ----------------------------
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: Build (no test)
        run: ./gradlew build -x test

      - name: Upload jar (temporary for downstream job)
        uses: actions/upload-artifact@v4
        with:
          name: be-jar
          path: build/libs/*.jar
          retention-days: 1

  # ----------------------------
  # 2. Test
  # ----------------------------
  test:
    name: Test (unit/integration)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: test (develop)
        if: ${{ github.base_ref == 'develop' }}
        env:
          SPRING_PROFILES_ACTIVE: ${{ vars.SPRING_PROFILES_ACTIVE_TEST }}
        run: ./gradlew test

      - name: Integration test + JaCoCo (main)
        if: ${{ github.base_ref == 'main' }}
        env:
          COVERAGE_MIN: ${{ vars.COVERAGE_MIN }}
          SPRING_PROFILES_ACTIVE: ${{ vars.SPRING_PROFILES_ACTIVE_TEST }}
        run: ./gradlew integrationTest jacocoTestReport jacocoTestCoverageVerification -PCOVERAGE_MIN=${{ env.COVERAGE_MIN }}

  # ----------------------------
  # 3. Static Analysis
  # ----------------------------
  static_analysis:
    name: Static Analysis (Sonar Cloud)
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.base_ref == 'develop' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Sonar Cloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build -x test sonar --info

  # ----------------------------
  # 4. Artifacts (develop)
  # ----------------------------
  artifacts:
    name: Upload Verified Artifact (develop)
    runs-on: ubuntu-latest
    needs: [build, test, static_analysis]
    if: ${{ github.base_ref == 'develop' }}

    steps:
      - name: Download built jar
        uses: actions/download-artifact@v4
        with:
          name: be-jar
          path: artifact

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: verified-be-jar
          path: artifact/*.jar
          retention-days: 90

  # ----------------------------
  # 5. Main → S3 Archive
  # ----------------------------
  main_archive:
    name: Archive release to S3
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.base_ref == 'main' }}

    steps:
      - name: Set meta
        id: meta
        run: |
          echo "timestamp=$(date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Download built jar
        uses: actions/download-artifact@v4
        with:
          name: be-jar
          path: artifact

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      - name: List artifact
        run: ls -la artifact && find artifact -maxdepth 2 -type f

      - name: Upload jar to S3
        env:
          BUCKET: ${{ secrets.RELEASE_BUCKET }}
          PREFIX: releases/backend
        run: |
          aws s3 cp artifact/ \
            s3://$BUCKET/$PREFIX/${{ steps.meta.outputs.timestamp }} \
            --recursive \
            --exclude "*" \
            --include "*.jar"
