apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
    notifications.argoproj.io/subscribe.on-health-degraded.discord: ""
spec:
  project: default
  source:
    repoURL: "https://github.com/100-hours-a-week/11-team-service-cloud.git"
    targetRevision: develop
    path: k8s/apps/ai/overlays/prod
  destination:
    server: "https://scuad-v3-prod-cp-nlb-2d0fce3ed45205e4.elb.ap-northeast-2.amazonaws.com:6443"
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
